### ISSUE TITLE
@nuxtjs/composition-api is always required

### ISSUE THREAD

**Issue by LionelPaulus** [storyblok/storyblok-nuxt-2#18]
Hi,

In the documentation, it seems you are giving us the choice to use the plugin with Composition API or not.
Then, the `@nuxtjs/composition-api` plugin should only be required if needed.

But currently, it's a basic requirement; a project using the `storyblok-nuxt-2` plugin without `@nuxtjs/composition-api` won't start.

<img width="778" alt="Screenshot 2022-06-17 at 15 16 23@2x" src="https://user-images.githubusercontent.com/789782/174305729-d53c8a64-8ac1-4e9a-bbb2-cfbf0b4d1164.png">

Would it be possible to fix that so that we are not required to add `@nuxtjs/composition-api` in our build?
It has a signifiant impact on build size.

Reproduction link: https://codesandbox.io/s/green-sun-45ptuw?file=/nuxt.config.js

Thanks!

**Comment by uuf6429** [comment]
This is a bit of a pain at the moment.. I already had to upgrade to node 14 from node 12, but node 14 is also not enough: the composition api requires node 14.20, but the latest stable on osx is 14.19 (!!)

Oh, and by the way, I had to downgrade from nuxt 3 because it does not properly handle static site generation (and the whole process is "experimental", undocumented and actually doesn't fully work well)

**Comment by SebbeJohansson** [comment]
I am still having the same issue and it sucks that Storyblok isnt doing anything to prevent this. I have a bunch of issues with my production site because of this.

**Comment by Dawntraoz** [comment]
Hi folks 👋
This was fixed in the v1.2.2 -> https://github.com/storyblok/storyblok-nuxt-2/releases/tag/v1.2.2

If you have any other issues, feel free to create a new issue. But take into account that some changes are coming to improve all the SDKs  🎉

**Comment by SebbeJohansson** [comment]
Finally! Great news 😍😍😍

**Comment by Dawntraoz** [comment]
Yes, @SebbeJohansson, sorry for the delays. I know you have been so active in open-source projects. It will be nice to have a call with you to see how we can improve the communications and make the SDKs better altogether.

We don't have (yet) a person dedicated to this, so having the help of folks like you can help us a lot 🤗

**Comment by SebbeJohansson** [comment]
@Dawntraoz I am mainly active in my private projects and the projects at work, but I understand what you mean.
I would love to! Feel free to contact me on my company email at sebastian.johansson@revolutionrace.se (since that is where you earn money from me ;) ).

Storyblok is the best CMS I have used (especially in combination with nuxt), so I would love to help in any way I can.
